motions:
  - open_both_hands
  - interact
  - wave
  - come_right_arm
  - shake_right
  - right_arm_up
  - count_right_hand
  - fist_right_hand
  - thumbs_up_right_arm
  - open_both_hands
  - interact
