#!/bin/bash

# Load helper variables and functions
source `echo $(dirname $(readlink -f ${BASH_SOURCE[0]}))`/test_joints_helpers.bash

# Determine if robot has Hey5 hands or three-finger hands. If unspecified, Hey5 hads are assumed.
has_hey5=true
if [[ $1 == '--full' ]]; then
  has_hey5=false
fi

# Check preconditions with user
YES_NO_MSG="Is the robot ${TXT_BF}secured to the crane${TXT_RESET} and "\
"${TXT_BF}standing with its feet on the ground?${TXT_RESET}"
_yes_no_question $YES_NO_MSG

# Start measuring time
START_TIME=$(date +%s.%N)

# Home pose
echo -e "${TXT_CYAN}Going to home pose...${TXT_RESET}"
_go_home
_play_motion "{motion_name: 'home_legs', skip_planning: true}"
echo "Done!"

# Head
echo -e "${TXT_CYAN}Testing head joints...${TXT_RESET}"
_move_joint head_1_joint 0.5
_move_joint head_1_joint -0.5
_move_joint head_1_joint 0.0

_move_joint head_2_joint 0.3
_move_joint head_2_joint -0.25
_move_joint head_2_joint 0.0

# Left arm
echo -e "${TXT_CYAN}Testing left arm joints...${TXT_RESET}"
_move_joint arm_left_4_joint 1.57
_move_joint arm_left_2_joint 1.31
_move_joint arm_left_1_joint 1.57
_move_joint arm_left_3_joint -1.57
_move_joint arm_left_5_joint 1.57
_move_joint arm_left_6_joint 1.57
_move_joint arm_left_6_joint 0.0
_move_joint arm_left_7_joint -1.41
_move_joint arm_left_7_joint 0.0

# Left hand
echo -e "${TXT_CYAN}Testing left hand joints...${TXT_RESET}"
if [[ $has_hey5 == true ]]; then
  _move_joint hand_left_thumb_joint 6.0 2.5
  _move_joint hand_left_thumb_joint 0.0 2.5
  _move_joint hand_left_index_joint 6.5 2.5
  _move_joint hand_left_index_joint 0.0 2.5
  _move_joint hand_left_mrl_joint   9.0 3.5
  _move_joint hand_left_mrl_joint   0.0 3.5
else
  _move_joint hand_left_thumb_joint 1.57
  _move_joint hand_left_thumb_joint 0.0
  _move_joint hand_left_index_joint 4.0  2.5
  _move_joint hand_left_index_joint 0.0  2.5
  _move_joint hand_left_middle_joint 4.0 2.5
  _move_joint hand_left_middle_joint 0.0 2.5
fi

_go_home

# Right arm
echo -e "${TXT_CYAN}Testing right arm joints...${TXT_RESET}"
_move_joint arm_right_4_joint 1.57
_move_joint arm_right_2_joint 1.31
_move_joint arm_right_1_joint 1.57
_move_joint arm_right_3_joint -1.57
_move_joint arm_right_5_joint 1.57
_move_joint arm_right_6_joint 1.57
_move_joint arm_right_6_joint 0.0
_move_joint arm_right_7_joint -1.41
_move_joint arm_right_7_joint 0.0

# Right hand
echo -e "${TXT_CYAN}Testing right hand joints...${TXT_RESET}"
if [[ $has_hey5 == true ]]; then
  _move_joint hand_right_thumb_joint 6.0 2.5
  _move_joint hand_right_thumb_joint 0.0 2.5
  _move_joint hand_right_index_joint 6.5 2.5
  _move_joint hand_right_index_joint 0.0 2.5
  _move_joint hand_right_mrl_joint   9.0 3.5
  _move_joint hand_right_mrl_joint   0.0 3.5
else
  _move_joint hand_right_thumb_joint 1.57
  _move_joint hand_right_thumb_joint 0.0
  _move_joint hand_right_index_joint 4.0  2.5
  _move_joint hand_right_index_joint 0.0  2.5
  _move_joint hand_right_middle_joint 4.0 2.5
  _move_joint hand_right_middle_joint 0.0 2.5
fi

# Torso
echo -e "${TXT_CYAN}Clearing arms from torso...${TXT_RESET}"
_play_motion "{motion_name: 'interact'}"
echo "Done!"

echo -e "${TXT_CYAN}Testing torso joints...${TXT_RESET}"
_move_joint torso_1_joint 0.3   2.0
_move_joint torso_1_joint -0.3  4.0
_move_joint torso_1_joint 0.0   2.0
_move_joint torso_2_joint 0.2   2.0
_move_joint torso_2_joint -0.15 3.5
_move_joint torso_2_joint 0.0   1.5

# Home pose
echo -e "${TXT_CYAN}Going to home pose...${TXT_RESET}"
_go_home
echo "Done!"

END_TIME=$(date +%s.%N)
DUR_STR=$(_duration_str $START_TIME $END_TIME)
echo -e "${TXT_GREEN}Upper body joints test finished successfully in ${DUR_STR}.${TXT_RESET}"
