#!/bin/bash

# Load helper variables and functions
source `echo $(dirname $(readlink -f ${BASH_SOURCE[0]}))`/test_joints_helpers.bash

# Check preconditions with user
YES_NO_MSG="Is the robot ${TXT_BF}secured to the crane${TXT_RESET} and ${TXT_BF}lifted so its feet do not touch the ground?${TXT_RESET}"
_yes_no_question $YES_NO_MSG

# Start measuring time
START_TIME=$(date +%s.%N)

# Initial pose
echo -e "${TXT_CYAN}Going to the initial pose...${TXT_RESET}"
_play_motion "{motion_name: 'interact'}"
_play_motion "{motion_name: 'home_legs', skip_planning: true}"
echo "Done!"

# Left leg
echo -e "${TXT_CYAN}Testing left leg joints...${TXT_RESET}"
_move_joint leg_left_4_joint  0.7854
_move_joint leg_left_3_joint -1.5708
_move_joint leg_left_4_joint  1.5708
_move_joint leg_left_1_joint  0.4 1.5
_move_joint leg_left_1_joint  0.0 1.5
_move_joint leg_left_2_joint  0.4 1.5
_move_joint leg_left_2_joint  0.0 1.5
_move_joint leg_left_5_joint -0.7854
_move_joint leg_left_5_joint  0.0
_move_joint leg_left_6_joint -0.4 1.5
_move_joint leg_left_6_joint  0.0 1.5
_play_motion "{motion_name: 'home_legs', skip_planning: true}"

# Right leg
echo -e "${TXT_CYAN}Testing right leg joints...${TXT_RESET}"
_move_joint leg_right_4_joint  0.7854
_move_joint leg_right_3_joint -1.5708
_move_joint leg_right_4_joint  1.5708
_move_joint leg_right_1_joint -0.4 1.5
_move_joint leg_right_1_joint  0.0 1.5
_move_joint leg_right_2_joint -0.4 1.5
_move_joint leg_right_2_joint  0.0 1.5
_move_joint leg_right_5_joint -0.7854
_move_joint leg_right_5_joint  0.0
_move_joint leg_right_6_joint  0.4 1.5
_move_joint leg_right_6_joint  0.0 1.5

# Home pose
echo -e "${TXT_CYAN}Going to home pose...${TXT_RESET}"
_play_motion "{motion_name: 'home_legs', skip_planning: true}"
_go_home
echo "Done!"

END_TIME=$(date +%s.%N)
DUR_STR=$(_duration_str $START_TIME $END_TIME)
echo -e "${TXT_GREEN}Lower body joints test finished successfully in ${DUR_STR}.${TXT_RESET}"
